version: '3'

networks:
    default:
        driver: bridge
    npm_proxy:
        name: npm_proxy
        driver: bridge
        ipam:
            config:
                - subnet: 172.30.0.0/24

services:
  ovpn1:
    container_name: openvpn-server-1
    image: shuricksumy/openvpn-server
    restart: always
    env_file:
      - ./.ovpn_env_basic
    network_mode: host
    devices:
        - /dev/net/tun
    cap_add:
        - NET_ADMIN
    volumes:
      - ./openvpn/openvpn1:/etc/openvpn
      - ./openvpn/easy-rsa:/etc/openvpn/easy-rsa
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID

  gui:
        image: shuricksumy/openvpn-ui
        container_name: openvpn-ui
        working_dir: /etc/openvpn/easy-rsa
        environment:
            - OPENVPN_ADMIN_USERNAME=admin # Leave this default as-is and update on first-run
            - OPENVPN_ADMIN_PASSWORD=admin # Leave this default as-is and update on first-run
            - SITE_NAME=Mikrotik
            - OPENVPN_SERVER_DOCKER_NAME=openvpn-server-1
            - OPENVPN_MANAGEMENT_ADDRESS=172.30.0.1:2088
        ports:
            - "8080:8080/tcp"
        restart: always
        networks:
            npm_proxy:
                ipv4_address: $IP_GUI
        volumes:
         -  /var/run/docker.sock:/var/run/docker.sock
         - ./openvpn/openvpn1:/etc/openvpn
         - ./openvpn/easy-rsa:/etc/openvpn/easy-rsa
         - ./openvpn/openvpn1/db:/opt/openvpn-gui-tap/db
